CC=gcc
CFLAGS=-Wall

libmsocket.a: msocket.o
            ar -rcs libmsocket.a msocket.o

msocket.o: msocket.c msocket.h
            $(CC) $(CFLAGS) -c msocket.c -lpthread

clean:
            rm -f libmsocket.a msocket.o
